-- ============================================================================
-- DevDocs Database Setup - Step 4: Insert Sample Data
-- ============================================================================
-- This script inserts sample solutions for testing
-- Run this AFTER creating tables, indexes, and triggers
-- ============================================================================

-- ============================================================================
-- Sample Solution 1: Python CORS Fix
-- ============================================================================

INSERT INTO solutions (
    title,
    description,
    code,
    language,
    tags,
    embedding
) VALUES (
    'Fix CORS error in FastAPI',
    'How to enable CORS in FastAPI when frontend is on different domain. Includes middleware setup and configuration for allowing cross-origin requests.',
    'from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()

# Configure CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Change to specific origins in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)',
    'python',
    ARRAY['cors', 'fastapi', 'web-development', 'middleware'],
    -- Mock embedding vector (384 dimensions of random values)
    -- In production, this will be generated by sentence-transformers model
    array_fill(0.0::float, ARRAY[384])::vector
);

-- ============================================================================
-- Sample Solution 2: JavaScript Array Sorting
-- ============================================================================

INSERT INTO solutions (
    title,
    description,
    code,
    language,
    tags,
    embedding
) VALUES (
    'Sort array of objects by property in JavaScript',
    'How to sort an array of objects by a specific property value in JavaScript. Works with numbers, strings, and dates. Includes ascending and descending order examples.',
    'const users = [
  { name: "John", age: 30 },
  { name: "Alice", age: 25 },
  { name: "Bob", age: 35 }
];

// Sort by age (ascending)
users.sort((a, b) => a.age - b.age);

// Sort by age (descending)
users.sort((a, b) => b.age - a.age);

// Sort by name (alphabetical)
users.sort((a, b) => a.name.localeCompare(b.name));

console.log(users);',
    'javascript',
    ARRAY['array', 'sorting', 'javascript', 'algorithms'],
    array_fill(0.1::float, ARRAY[384])::vector
);

-- ============================================================================
-- Sample Solution 3: Python Async Database Query
-- ============================================================================

INSERT INTO solutions (
    title,
    description,
    code,
    language,
    tags,
    embedding
) VALUES (
    'SQLAlchemy async session with PostgreSQL',
    'How to create and use async SQLAlchemy sessions with PostgreSQL in FastAPI. Includes session factory setup, dependency injection, and proper transaction handling.',
    'from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker

# Create async engine
engine = create_async_engine(
    "postgresql+asyncpg://user:password@localhost/dbname",
    echo=True,
    future=True
)

# Create session factory
async_session = sessionmaker(
    engine, class_=AsyncSession, expire_on_commit=False
)

# Dependency for FastAPI
async def get_db():
    async with async_session() as session:
        yield session',
    'python',
    ARRAY['sqlalchemy', 'async', 'postgresql', 'fastapi', 'database'],
    array_fill(0.2::float, ARRAY[384])::vector
);

-- ============================================================================
-- Sample Solution 4: React useState Hook
-- ============================================================================

INSERT INTO solutions (
    title,
    description,
    code,
    language,
    tags,
    embedding
) VALUES (
    'React useState hook with TypeScript',
    'How to use React useState hook with proper TypeScript types. Includes examples for primitives, objects, and arrays with type safety.',
    'import { useState } from "react";

// String state
const [name, setName] = useState<string>("");

// Number state
const [count, setCount] = useState<number>(0);

// Object state with interface
interface User {
  id: number;
  name: string;
  email: string;
}

const [user, setUser] = useState<User | null>(null);

// Array state
const [items, setItems] = useState<string[]>([]);

// Update object state
setUser({ id: 1, name: "John", email: "john@example.com" });

// Update array state
setItems([...items, "new item"]);',
    'typescript',
    ARRAY['react', 'typescript', 'hooks', 'useState', 'frontend'],
    array_fill(0.3::float, ARRAY[384])::vector
);

-- ============================================================================
-- Sample Solution 5: Python JWT Authentication
-- ============================================================================

INSERT INTO solutions (
    title,
    description,
    code,
    language,
    tags,
    embedding
) VALUES (
    'JWT token generation and verification in Python',
    'How to create and verify JWT tokens in Python using PyJWT library. Includes token encoding with expiration, decoding, and error handling for authentication.',
    'import jwt
from datetime import datetime, timedelta

SECRET_KEY = "your-secret-key-here"
ALGORITHM = "HS256"

# Generate JWT token
def create_token(user_id: str) -> str:
    payload = {
        "user_id": user_id,
        "exp": datetime.utcnow() + timedelta(hours=24)
    }
    token = jwt.encode(payload, SECRET_KEY, algorithm=ALGORITHM)
    return token

# Verify JWT token
def verify_token(token: str) -> dict:
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        return payload
    except jwt.ExpiredSignatureError:
        raise Exception("Token has expired")
    except jwt.InvalidTokenError:
        raise Exception("Invalid token")',
    'python',
    ARRAY['jwt', 'authentication', 'security', 'python', 'tokens'],
    array_fill(0.4::float, ARRAY[384])::vector
);

-- ============================================================================
-- Verification Query
-- ============================================================================

-- Check all sample data was inserted successfully
SELECT 
    id,
    title,
    language,
    array_length(tags, 1) as tag_count,
    created_at
FROM solutions
ORDER BY created_at DESC;

-- Count total solutions
SELECT COUNT(*) as total_solutions FROM solutions;
